let localAbort=null;
let voiceRecognition=null;
const SUPPORTED={"en-US":"en-US","uk-UA":"uk-UA","pl-PL":"pl-PL","es-ES":"es-ES","ru-RU":"ru-RU"};
function appVoiceLocale(){const chosen=document.getElementById("aiShopVoiceLanguage")?.value||"auto";if(chosen!=="auto")return SUPPORTED[chosen]||"en-US";const lang=String(document.documentElement.lang||navigator.language||"en-US").toLowerCase();if(lang.startsWith("uk"))return "uk-UA";if(lang.startsWith("pl"))return "pl-PL";if(lang.startsWith("es"))return "es-ES";if(lang.startsWith("ru"))return "ru-RU";return "en-US"}
function setBusy(busy,processingId){document.querySelectorAll("#proPanelAitools [data-ai-action]").forEach(b=>b.disabled=busy);document.getElementById(processingId)?.classList.toggle("hidden",!busy)}
async function aiCall(endpoint,payload,processingId){setBusy(true,processingId);try{const r=await fetch(endpoint,{method:"POST",headers:window.authHeaders?.({"Content-Type":"application/json"})||{"Content-Type":"application/json"},body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`AI request failed (${r.status})`);return d.result??d.translation??""}finally{setBusy(false,processingId)}}
window.startVoiceNote=function(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){window.showToast?.("Live dictation requires Chrome or Edge with Web Speech support.","warning",7000);return}if(voiceRecognition){try{voiceRecognition.stop()}catch{}return}const textarea=document.getElementById("aiShopText"),btn=document.getElementById("aiShopMicButton"),state=document.getElementById("aiShopVoiceState");const r=new SR();voiceRecognition=r;r.lang=appVoiceLocale();r.continuous=true;r.interimResults=true;let committed=(textarea?.value||"").trim();r.onstart=()=>{btn?.classList.add("recording");btn?.setAttribute("aria-pressed","true");if(state)state.textContent=`Listening — ${r.lang}`};r.onresult=e=>{let finalChunk="",interim="";for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0]?.transcript||"";if(e.results[i].isFinal)finalChunk+=t+" ";else interim+=t}if(finalChunk.trim())committed=[committed,finalChunk.trim()].filter(Boolean).join(" ");if(textarea)textarea.value=[committed,interim.trim()].filter(Boolean).join(" ");if(state)state.textContent=`Listening — ${r.lang}`};r.onerror=e=>{if(e.error!=="no-speech")window.showToast?.(`Voice dictation: ${e.error}`,"warning",6000)};r.onend=()=>{voiceRecognition=null;btn?.classList.remove("recording");btn?.setAttribute("aria-pressed","false");if(state)state.textContent="Ready for dictation"};try{r.start()}catch(e){voiceRecognition=null;window.showToast?.(e.message,"error")}};
window.aiProfessionalNote=async function(mode="professional"){const el=document.getElementById("aiShopText"),out=document.getElementById("aiShopResult"),text=el?.value.trim();if(!text)return window.showToast?.("Enter or dictate a mechanic note first.","warning");try{const x=await aiCall("/api/ai/note",{text,mode},"aiShopProcessing");if(out)out.textContent=x||""}catch(e){if(out)out.textContent=e.message;window.showToast?.(e.message,"error",7000)}};
window.aiDiagnosticAssistant=async function(){const el=document.getElementById("aiDiagnosticInput"),out=document.getElementById("aiDiagnosticResult"),text=el?.value.trim();if(!text)return window.showToast?.("Enter symptoms or fault codes first.","warning");try{const x=await aiCall("/api/ai/diagnostic",{text},"aiDiagnosticProcessing");if(out)out.textContent=x||""}catch(e){if(out)out.textContent=e.message;window.showToast?.(e.message,"error",7000)}};
window.aiPartAssistant=async function(){const q=document.getElementById("aiPartQuery")?.value.trim(),vin=document.getElementById("aiPartVin")?.value.trim(),out=document.getElementById("aiPartResult");if(!q)return window.showToast?.("Enter a part number or description first.","warning");try{const x=await aiCall("/api/ai/part",{vin,query:q},"aiPartProcessing");if(out)out.textContent=x||""}catch(e){if(out)out.textContent=e.message;window.showToast?.(e.message,"error",7000)}};
export async function mount(scope){localAbort=new AbortController();scope.on(scope.host,"ittr:module-refresh",()=>window.renderProCenter?.(),{passive:true});await window.renderProCenter?.();setTimeout(()=>window.checkAIConnection?.(),0)}
export async function afterShow(){await window.renderProCenter?.()}
export function unmount(){localAbort?.abort();localAbort=null;if(voiceRecognition){try{voiceRecognition.stop()}catch{}voiceRecognition=null}}

async function reconcileFullbayHistory(){
 if(!requireAdmin())return;
 const box=document.getElementById("fullbayImportStatus");if(box)box.textContent="Auditing customer/unit/history links…";
 try{
  const d=await apiJSON("/api/fullbay/history/reconcile",{method:"POST",body:"{}"}),r=d.report||{};
  alert(`History audit complete.\n\nCustomer links repaired: ${r.customerLinks||0}\nUnit links repaired: ${r.unitLinks||0}\nMetadata backfilled: ${r.metadataBackfill||0}\nHistory rows still without a unit: ${r.orphanHistory||0}\nUnits with non-standard/short VIN or serial: ${r.invalidVinUnits||0}\nDuplicate customer + unit-number groups: ${r.duplicateCustomerUnits||0}\n\nNo records were deleted.`);
  await renderFullbayImportStatus();
 }catch(e){alert(e.message||"History audit failed.");if(box)box.textContent=e.message||"History audit failed."}
}

let samsaraFleetCache=[];
async function loadSamsaraFleet(){const status=document.getElementById('samsaraStatus'),out=document.getElementById('samsaraFleetResults');if(status)status.textContent='Connecting to Samsara…';try{const s=await apiJSON('/api/samsara/status');if(!s.configured){status.innerHTML='<b>Samsara is ready but the token is not configured.</b> Add SAMSARA_API_TOKEN in Railway Variables.';if(out)out.innerHTML='';return}if(!s.connected)throw new Error(s.error||'Samsara connection failed.');const d=await apiJSON('/api/samsara/fleet');samsaraFleetCache=d.items||[];status.textContent=`Connected · ${samsaraFleetCache.length} vehicles · Updated ${fmtDateTime(d.updatedAt)}`;renderSamsaraFleet()}catch(e){if(status)status.innerHTML=`<span class="error">${esc(e.message||'Samsara unavailable.')}</span>`}}
function renderSamsaraFleet(){
 const out=document.getElementById('samsaraFleetResults');if(!out)return;
 const q=String(document.getElementById('samsaraSearch')?.value||document.getElementById('samsaraFleetSearch')?.value||'').toLowerCase().trim();
 const rows=samsaraFleetCache.filter(v=>!q||[v.name,v.vin,v.licensePlate,v.driver?.name,v.gps?.location,v.make,v.model].join(' ').toLowerCase().includes(q));
 const faultCell=v=>{const n=Number(v.faultCount||0),has=!!v.hasDiagnosticData||!!v.faultCodes;if(!has)return 'None reported';const label=n>0?'⚠️ '+n+' Fault Code'+(n===1?'':'s'):'⚠️ View Diagnostics';return '<button type="button" class="ittr-fault-btn" data-fault-id="'+esc(v.id)+'" data-fault-name="'+esc(v.name||'Vehicle')+'" style="background:#fee2e2;color:#b91c1c;border:1px solid #fecaca;border-radius:8px;padding:6px 9px;font-weight:700;cursor:pointer">'+label+'</button>'};
 out.innerHTML=rows.length?'<div class="tableWrap"><table><thead><tr><th>Vehicle</th><th>VIN / Plate</th><th>Driver</th><th>Engine</th><th>Speed</th><th>Mileage</th><th>Engine Hrs</th><th>Faults</th><th>Last Location</th><th>Updated</th></tr></thead><tbody>'+rows.map(v=>{const raw=v.gpsSpeedMph?.value,sp=(raw===null||raw===undefined||raw==='')?null:Number(raw),speed=Number.isFinite(sp)?Math.round(sp)+' mph':'—';return '<tr><td><b>'+esc(v.name||'—')+'</b><div class="muted">'+esc([v.year,v.make,v.model].filter(Boolean).join(' '))+'</div></td><td>'+esc(v.vin||'—')+'<div class="muted">'+esc(v.licensePlate||'')+'</div></td><td>'+esc(v.driver?.name||'—')+'</td><td>'+esc(v.engineModel||'—')+'</td><td>'+esc(speed)+'</td><td>'+(v.odometerMiles!=null?esc(Number(v.odometerMiles).toLocaleString(undefined,{maximumFractionDigits:1})+' mi'):'—')+(v.odometerSource?'<div class="muted">'+esc(v.odometerSource)+'</div>':'')+'</td><td>'+(v.engineHours!=null?esc(Number(v.engineHours).toLocaleString(undefined,{maximumFractionDigits:1})+' h'):'—')+'</td><td>'+faultCell(v)+'</td><td>'+esc(v.gps?.location||v.gps?.reverseGeo?.formattedLocation||((v.gps?.latitude!=null&&v.gps?.longitude!=null)?Number(v.gps.latitude).toFixed(5)+', '+Number(v.gps.longitude).toFixed(5):'—'))+'</td><td>'+esc(v.gps?.time?fmtDateTime(v.gps.time):'—')+'</td></tr>'}).join('')+'</tbody></table></div>':'<div class="muted">No Samsara vehicles match this search.</div>';
 out.querySelectorAll('[data-fault-id]').forEach(btn=>btn.onclick=()=>window.openSamsaraFaultModal?.(btn.dataset.faultId,btn.dataset.faultName));
}
async function auditDuplicateCustomers(){
 const out=document.getElementById('duplicateCustomerResults');if(out)out.textContent='Scanning customers…';
 try{
  const d=await apiJSON('/api/customers/duplicate-audit'),groups=d.candidates||[];
  out.innerHTML=groups.length?groups.map((g,gi)=>`<div class="card" style="margin:10px 0">
   <b>${esc(g.normalized)}</b><div class="muted">${esc(g.reason)}</div>
   ${g.customers.map((c,ci)=>`<label style="display:flex;gap:10px;align-items:flex-start;padding:9px 0;border-bottom:1px solid var(--line,#ddd)">
    <input type="radio" name="dupMaster${gi}" value="${Number(c.id)}" ${ci===0?'checked':''}>
    <span><b>${esc(c.customer_name)}</b><div class="muted">DOT ${esc(c.usdot||'—')} · ${c.units||0} units · ${c.history||0} history records · Fullbay ${esc(c.fullbay_id||'—')}</div></span>
   </label>`).join('')}
   <div class="actions" style="margin-top:10px"><button class="secondary" onclick="previewDuplicateMerge(${gi})">Review Merge</button></div>
   <div id="dupMergePreview${gi}"></div>
  </div>`).join(''):`<div class="success">No normalized-name duplicates found. Scanned ${d.scanned||0} customers.</div>`;
  window.__duplicateAuditGroups=groups;
 }catch(e){if(out)out.innerHTML=`<div class="error">${esc(e.message||'Duplicate audit failed.')}</div>`}
}
async function previewDuplicateMerge(groupIndex){
 const g=(window.__duplicateAuditGroups||[])[groupIndex];if(!g)return;
 const masterId=Number(document.querySelector(`input[name="dupMaster${groupIndex}"]:checked`)?.value||0);
 const duplicateIds=g.customers.filter(c=>Number(c.id)!==masterId).map(c=>Number(c.id));
 const box=document.getElementById(`dupMergePreview${groupIndex}`);
 if(duplicateIds.length!==1){box.innerHTML='<div class="error">This group has more than two records. Merge one pair at a time.</div>';return}
 const duplicateId=duplicateIds[0];
 try{
  const p=await apiJSON('/api/customers/merge-preview',{method:'POST',body:JSON.stringify({masterId,duplicateId})});
  const master=p.customers.find(c=>Number(c.id)===masterId),dup=p.customers.find(c=>Number(c.id)===duplicateId),dc=p.counts[duplicateId]||{};
  box.innerHTML=`<div class="notice" style="margin-top:10px"><b>MERGE PREVIEW — nothing changed yet</b><br>
   Keep: <b>${esc(master?.customer_name||masterId)}</b><br>
   Merge into it: <b>${esc(dup?.customer_name||duplicateId)}</b><br>
   Will relink: ${dc.units||0} units · ${dc.history||0} history records · ${dc.invoices||0} invoices · ${dc.service_orders||0} service orders.
   <div style="margin-top:8px"><input id="dupConfirm${groupIndex}" placeholder="Type MERGE" style="max-width:150px">
   <button class="danger" onclick="commitDuplicateMerge(${groupIndex},${masterId},${duplicateId})">Merge Customer</button></div></div>`;
 }catch(e){box.innerHTML=`<div class="error"><b>Merge preview could not load.</b><br>${esc(e.message||'Merge preview failed.')}</div>`}
}
async function commitDuplicateMerge(groupIndex,masterId,duplicateId){
 const typed=String(document.getElementById(`dupConfirm${groupIndex}`)?.value||'').trim().toUpperCase();
 if(typed!=='MERGE'){alert('Type MERGE exactly before continuing.');return}
 if(!confirm('This will relink the duplicate customer records to the selected master. Continue?'))return;
 try{
  const r=await apiJSON('/api/customers/merge',{method:'POST',body:JSON.stringify({masterId,duplicateId})});
  alert(`Merge complete. ${r.movedUnits||0} units moved, ${r.mergedUnits||0} duplicate units consolidated, ${r.historyMoved||0} history rows, ${r.invoicesMoved||0} invoices, ${r.serviceOrdersMoved||0} service orders relinked.`);
  await auditDuplicateCustomers();
 }catch(e){alert(e.message||'Customer merge failed.')}
}

// v24.24.5 lazy-route global action exports
window.loadSamsaraFleet = loadSamsaraFleet;
window.renderSamsaraFleet = renderSamsaraFleet;
window.auditDuplicateCustomers = auditDuplicateCustomers;
window.previewDuplicateMerge = previewDuplicateMerge;
window.commitDuplicateMerge = commitDuplicateMerge;

async function auditImportedFullbayHistory(){
 const out=document.getElementById('fullbayHistoryResetResults');if(out)out.textContent='Auditing imported Fullbay history…';
 try{const d=await apiJSON('/api/fullbay/history/import-audit');
 out.innerHTML=`<div class="notice"><b>${d.imported||0} imported Fullbay history rows found.</b><br>${d.incomplete||0} appear incomplete.<br>${d.aiHistory||0} AI-added history rows are protected from this cleanup.
 <div style="margin-top:10px"><input id="fullbayDeleteConfirm" placeholder="Type DELETE FULLBAY HISTORY" style="min-width:270px"><button class="danger" onclick="deleteImportedFullbayHistory()">Delete Imported Fullbay History</button></div>
 <div class="muted" style="margin-top:7px">Customers, units, ITTR invoices, ITTR work orders and inventory are preserved.</div></div>`}
 catch(e){out.innerHTML=`<div class="error">${esc(e.message||'Fullbay history audit failed.')}</div>`}
}
async function deleteImportedFullbayHistory(){
 const confirmation=String(document.getElementById('fullbayDeleteConfirm')?.value||'').trim();
 if(confirmation!=='DELETE FULLBAY HISTORY'){alert('Type DELETE FULLBAY HISTORY exactly.');return}
 if(!confirm('Delete ONLY the previously imported Fullbay service-history rows? Customers, units, ITTR invoices/work orders and inventory will remain.'))return;
 try{const r=await apiJSON('/api/fullbay/history/delete-imported',{method:'POST',body:JSON.stringify({confirmation})});
 alert(`${r.deleted||0} imported Fullbay history rows deleted. Customers, units and ITTR records were preserved.`);await auditImportedFullbayHistory()}
 catch(e){alert(e.message||'Fullbay history cleanup failed.')}
}
window.auditImportedFullbayHistory=auditImportedFullbayHistory;
window.deleteImportedFullbayHistory=deleteImportedFullbayHistory;

window.previewSamsaraUnitSync=async function(){const b=document.getElementById('samsaraSyncSummary'),r=document.getElementById('samsaraSyncReview');try{if(b)b.textContent='Checking Samsara against ITTR units…';const d=await apiJSON('/api/samsara/unit-sync/preview');if(b)b.innerHTML=`<b>Preview:</b> ${d.totalSamsara} Samsara · ${d.totalIttr} ITTR · <b>${d.matched} matched</b> · ${d.ambiguous+d.unmatched} need review`;if(r)r.innerHTML=(d.items||[]).filter(x=>x.matchStatus!=='matched').map(x=>`<div class="notice" style="margin-top:8px"><b>${esc(x.name||x.unit||'Unnamed')}</b> · VIN ${esc(x.vin||'—')} · ${x.matchStatus}</div>`).join('')||'<div class="notice">All Samsara vehicles safely matched.</div>'}catch(e){if(b)b.innerHTML=`<span style="color:#b42318"><b>Preview failed:</b> ${esc(e.detail||e.message||String(e))}</span>`}};
window.syncSamsaraUnits=async function(){if(!confirm('Sync Samsara to existing ITTR units? Uncertain matches will be skipped.'))return;const b=document.getElementById('samsaraSyncSummary');try{const d=await apiJSON('/api/samsara/unit-sync',{method:'POST',body:{}});if(b)b.innerHTML=`<b>Complete:</b> ${d.updated} updated · ${d.linked} newly linked · ${d.ambiguous+d.unmatched} need review`;showToast?.(`Samsara updated ${d.updated} unit(s).`,'success',6000);await previewSamsaraUnitSync()}catch(e){if(b)b.innerHTML=`<span style="color:#b42318"><b>Sync failed:</b> ${esc(e.detail||e.message||String(e))}${String(e.detail||e.message||e).includes('API endpoint not found')?' — backend route is missing or Railway is still running an older server build.':''}</span>`}};
window.loadSamsaraAllUnits=async function(){const b=document.getElementById('samsaraSyncSummary'),r=document.getElementById('samsaraSyncReview');try{const d=await apiJSON('/api/samsara/all-units');if(b)b.innerHTML=`<b>All ITTR Units:</b> ${d.items.length} · ${d.items.filter(x=>x.samsaraStatus==='connected').length} Samsara connected`;if(r)r.innerHTML=`<div class="tableWrap"><table><thead><tr><th>Customer</th><th>Unit</th><th>VIN</th><th>Samsara</th><th>Driver</th><th>Location</th></tr></thead><tbody>${d.items.map(x=>`<tr><td>${esc(x.customer_name||'—')}</td><td><b>${esc(x.unit_number||'—')}</b></td><td>${esc(x.vin||'—')}</td><td>${x.samsaraStatus==='connected'?'<b style="color:#067647">Connected</b>':'Not connected'}</td><td>${esc(x.samsara_driver_name||'—')}</td><td>${esc(x.samsara_location||'—')}</td></tr>`).join('')}</tbody></table></div>`}catch(e){if(r)r.textContent=e.message||e}};


window.runSamsaraDiagnostics=async function(){const b=document.getElementById('samsaraSyncSummary'),r=document.getElementById('samsaraSyncReview');try{if(b)b.textContent='Checking running build, Railway database, Samsara token, schema and Samsara API…';const resp=await fetch('/api/samsara/diagnostics',{credentials:'same-origin',cache:'no-store',headers:window.authHeaders?.({Accept:'application/json'})||{Accept:'application/json'}});let d;try{d=await resp.json()}catch(_){throw new Error(`Diagnostics returned HTTP ${resp.status} instead of JSON`)}const env=d.env||{},db=d.database||{},sa=d.samsara||{},sc=d.schema||{},mk=v=>v?'✓':'✗';if(b)b.innerHTML=`<b>Build ${esc(d.build||'UNKNOWN')}</b> · DATABASE_URL ${mk(env.databaseUrlPresent)} · Database ${mk(db.ok)} · SAMSARA_API_TOKEN ${mk(env.samsaraTokenPresent)} · Schema ${mk(sc.ok)} · Samsara API ${mk(sa.ok)} · Vehicles ${Number(sa.vehicleCount||0)}`;const x=[];if(!env.databaseUrlPresent)x.push('DATABASE_URL is not visible to this running Railway service.');if(env.databaseUrlPresent&&!db.ok)x.push('Database connection failed: '+(db.reason||'unknown error'));if(sc.reason)x.push('Schema check failed: '+sc.reason);if(sc.missing?.length)x.push('Missing unit columns: '+sc.missing.join(', '));if(!env.samsaraTokenPresent)x.push('SAMSARA_API_TOKEN is not visible to this running Railway service.');if(env.samsaraTokenPresent&&!sa.ok)x.push(`Samsara API failed${sa.httpStatus?' (HTTP '+sa.httpStatus+')':''}: ${sa.reason||'unknown error'}`);if(r)r.innerHTML=x.map(v=>`<div class="notice" style="margin-top:8px;color:#b42318"><b>Diagnostic:</b> ${esc(v)}</div>`).join('')+(d.ok?`<div class="notice" style="margin-top:8px;color:#067647"><b>All checks passed.</b> ${Number(sa.vehicleCount||0)} Samsara vehicle(s) returned. Run Preview Unit Matches next.</div>`:'')}catch(e){if(b)b.innerHTML=`<span style="color:#b42318"><b>Diagnostic failed:</b> ${esc(e.message||String(e))}</span>`}};
let samsaraDriversCache=[];window.loadSamsaraDrivers=async function(){const out=document.getElementById('samsaraDriverResults');try{if(out)out.innerHTML='<div class="muted">Loading drivers…</div>';const d=await apiJSON('/api/samsara/drivers');samsaraDriversCache=d.items||[];renderSamsaraDrivers()}catch(e){if(out)out.innerHTML='<div class="notice error">'+esc(e.message||String(e))+'</div>'}};window.renderSamsaraDrivers=function(){const out=document.getElementById('samsaraDriverResults');if(!out)return;const q=String(document.getElementById('samsaraDriverSearch')?.value||'').toLowerCase(),rows=samsaraDriversCache.filter(d=>!q||[d.name,d.phone,d.licenseNumber,d.username].join(' ').toLowerCase().includes(q));out.innerHTML=rows.map(d=>'<button class="btn" style="display:block;width:100%;text-align:left;margin:6px 0" onclick="openSamsaraDriver(\''+esc(d.id)+'\')"><b>'+esc(d.name||'Unnamed driver')+'</b>'+(d.phone?' · '+esc(d.phone):'')+(d.licenseNumber?' · License '+esc(d.licenseNumber):'')+'</button>').join('')||'<div class="muted">No drivers found.</div>'};window.openSamsaraDriver=async function(id){if(!samsaraDriversCache.length)await loadSamsaraDrivers();const d=samsaraDriversCache.find(x=>String(x.id)===String(id)),out=document.getElementById('samsaraDriverProfile');if(!out||!d)return;out.innerHTML='<div class="card"><h3>'+esc(d.name||'Driver')+'</h3>'+(d.profileImageUrl?'<img src="'+esc(d.profileImageUrl)+'" alt="" style="width:80px;height:80px;border-radius:50%;object-fit:cover">':'')+'<p><b>Phone:</b> '+esc(d.phone||'—')+'<br><b>License:</b> '+esc(d.licenseNumber||'—')+(d.licenseState?' · '+esc(d.licenseState):'')+'<br><b>Status:</b> '+esc(d.activationStatus||'—')+'<br><b>Username:</b> '+esc(d.username||'—')+'<br><b>Timezone:</b> '+esc(d.timezone||'—')+'<br><b>Assigned vehicle:</b> '+esc(d.currentAssignment?.vehicle?.name||d.staticAssignedVehicle?.name||d.currentAssignment?.vehicleId||'—')+(d.currentAssignment?.assignmentType?' · '+esc(d.currentAssignment.assignmentType):'')+'</p>'+(d.notes?'<p><b>Notes:</b> '+esc(d.notes)+'</p>':'')+'</div>';out.scrollIntoView({behavior:'smooth',block:'nearest'})};

function ittrFmtSamsaraTime(x){if(!x)return '—';const d=new Date(x);return Number.isNaN(d.getTime())?'—':d.toLocaleString()}
function ittrSamsaraLocation(v){const g=v?.gps;if(!g)return '—';return g.reverseGeo?.formattedLocation||g.location||((g.latitude!=null&&g.longitude!=null)?Number(g.latitude).toFixed(5)+', '+Number(g.longitude).toFixed(5):'—')}
window.openSamsaraFaultModal=async function(vehicleId,vehicleName){let m=document.getElementById('samsaraFaultModal');if(!m){m=document.createElement('div');m.id='samsaraFaultModal';m.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:100000;display:none;align-items:center;justify-content:center;padding:18px';m.innerHTML='<div style="background:#fff;color:#111;width:min(900px,96vw);max-height:88vh;overflow:auto;border-radius:14px;padding:20px;box-shadow:0 20px 60px #0005"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><h2 id="samsaraFaultTitle" style="margin:0">Fault Codes</h2><button class="btn" onclick="document.getElementById(\'samsaraFaultModal\').style.display=\'none\'">Close</button></div><div id="samsaraFaultBody" style="margin-top:14px"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.style.display='none'})}m.style.display='flex';document.getElementById('samsaraFaultTitle').textContent=(vehicleName||'Vehicle')+' · Active Fault Codes';const body=document.getElementById('samsaraFaultBody');body.innerHTML='<div class="muted">Loading live diagnostic reading…</div>';try{const d=await apiJSON('/api/samsara/vehicle-faults?vehicleId='+encodeURIComponent(vehicleId));if(!d.faults?.length){body.innerHTML='<div class="notice">No active J1939 SPN/FMI codes were returned in the latest Samsara reading.</div>';return}body.innerHTML='<div class="muted" style="margin-bottom:10px">Latest reading: '+esc(ittrFmtSamsaraTime(d.time))+'</div><div style="overflow:auto"><table class="table"><thead><tr><th>SPN</th><th>FMI</th><th>Description</th><th>Occurrences</th><th>Status</th></tr></thead><tbody>'+d.faults.map(z=>'<tr><td><b>'+esc(z.spn??'—')+'</b></td><td>'+esc(z.fmi??'—')+'</td><td>'+esc(z.description||'—')+'</td><td>'+esc(z.occurrenceCount??'—')+'</td><td>'+(z.active===false?'Inactive':'Active')+'</td></tr>').join('')+'</tbody></table></div>'}catch(e){body.innerHTML='<div class="notice error">'+esc(e.message||String(e))+'</div>'}}
window.renderSamsaraFleet=function(){const out=document.getElementById('samsaraFleetResults');if(!out)return;const q=String(document.getElementById('samsaraFleetSearch')?.value||'').trim().toLowerCase(),rows=(window.samsaraFleetCache||samsaraFleetCache||[]).filter(v=>!q||[v.name,v.vin,v.licensePlate,v.driver?.name,ittrSamsaraLocation(v)].join(' ').toLowerCase().includes(q));out.innerHTML='<div style="overflow:auto"><table class="table"><thead><tr><th>Vehicle</th><th>VIN / Plate</th><th>Driver</th><th>Engine</th><th>Speed</th><th>Mileage</th><th>Engine Hrs</th><th>Faults</th><th>Last Location</th><th>Updated</th></tr></thead><tbody>'+rows.map(v=>{const sp=Number(v.gpsSpeedMph?.value),speed=Number.isFinite(sp)?sp.toFixed(sp%1?1:0)+' mph':'—',fc=Number(v.faultCount||0),faultBtn=fc>0?'<button class="btn btn-sm" onclick="openSamsaraFaultModal(\''+esc(v.id)+'\',\''+esc(String(v.name||'').replace(/'/g,'&#39;'))+'\')">⚠️ '+fc+' Fault Code'+(fc===1?'':'s')+'</button>':(v.faultCodes?'<button class="btn btn-sm" onclick="openSamsaraFaultModal(\''+esc(v.id)+'\',\''+esc(String(v.name||'').replace(/'/g,'&#39;'))+'\')">View diagnostics</button>':'None reported');return '<tr><td><b>'+esc(v.name||'—')+'</b><br><span class="muted">'+esc([v.year,v.make,v.model].filter(Boolean).join(' '))+'</span></td><td>'+esc(v.vin||'—')+(v.licensePlate?'<br>'+esc(v.licensePlate):'')+'</td><td>'+esc(v.driver?.name||'—')+'</td><td>'+esc(v.engineModel||v.engineState||'—')+'</td><td>'+esc(speed)+'</td><td>'+(v.odometerMiles!=null?esc(Number(v.odometerMiles).toLocaleString(undefined,{maximumFractionDigits:1})+' mi'):'—')+'</td><td>'+(v.engineHours!=null?esc(Number(v.engineHours).toLocaleString(undefined,{maximumFractionDigits:1})+' h'):'—')+'</td><td>'+faultBtn+'</td><td>'+esc(ittrSamsaraLocation(v))+'</td><td>'+esc(ittrFmtSamsaraTime(v.gps?.time||v.gpsSpeedMph?.time))+'</td></tr>'}).join('')+'</tbody></table></div>'}

;(function(){
 const css='.ittr-fault-btn{background:#fee2e2!important;color:#b91c1c!important;border:1px solid #fecaca!important;font-weight:700}.ittr-fault-overlay{position:fixed;inset:0;background:rgba(15,23,42,.58);z-index:100000;display:flex;align-items:center;justify-content:center;padding:18px}.ittr-fault-card{background:#fff;color:#111827;width:min(920px,96vw);max-height:88vh;overflow:auto;border-radius:16px;padding:20px;box-shadow:0 24px 80px #0006}.ittr-fault-table{width:100%;border-collapse:collapse}.ittr-fault-table th,.ittr-fault-table td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left}';if(!document.getElementById('ittrSamsaraFaultCss')){const st=document.createElement('style');st.id='ittrSamsaraFaultCss';st.textContent=css;document.head.appendChild(st)}
 window.openFaultModal=window.openSamsaraFaultModal=async function(vehicleId,vehicleName){let m=document.getElementById('samsaraFaultModal');if(!m){m=document.createElement('div');m.id='samsaraFaultModal';m.className='ittr-fault-overlay';m.innerHTML='<div class="ittr-fault-card"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h2 id="samsaraFaultTitle" style="margin:0">Fault Codes</h2><button class="btn" id="samsaraFaultClose">Close</button></div><div id="samsaraFaultBody" style="margin-top:14px"></div></div>';document.body.appendChild(m);m.onclick=e=>{if(e.target===m)m.remove()};m.querySelector('#samsaraFaultClose').onclick=()=>m.remove()}document.getElementById('samsaraFaultTitle').textContent=(vehicleName||'Vehicle')+' · Active J1939 Fault Codes';const body=document.getElementById('samsaraFaultBody');body.innerHTML='<div class="muted">Loading current Samsara diagnostics…</div>';try{const d=await apiJSON('/api/samsara/vehicle-faults?vehicleId='+encodeURIComponent(vehicleId));if(!d.faults?.length){body.innerHTML='<div class="notice">No active J1939 SPN/FMI codes in the latest Samsara fault reading.</div>';return}body.innerHTML='<div class="muted" style="margin-bottom:10px">Updated '+esc(d.time?new Date(d.time).toLocaleString():'—')+'</div><div style="overflow:auto"><table class="ittr-fault-table"><thead><tr><th>SPN</th><th>FMI</th><th>Description</th><th>Occurrence Count</th><th>Status</th></tr></thead><tbody>'+d.faults.map(z=>'<tr><td><b>SPN '+esc(z.spn??'—')+'</b></td><td>FMI '+esc(z.fmi??'—')+'</td><td>'+esc(z.description||'—')+'</td><td>'+esc(z.occurrenceCount??'—')+'</td><td>'+(z.active===false?'Inactive':'Active')+'</td></tr>').join('')+'</tbody></table></div>'}catch(e){body.innerHTML='<div class="notice error">'+esc(e.message||String(e))+'</div>'}}
 const loc=v=>v?.gps?.reverseGeo?.formattedLocation||v?.gps?.location||((v?.gps?.latitude!=null&&v?.gps?.longitude!=null)?Number(v.gps.latitude).toFixed(5)+', '+Number(v.gps.longitude).toFixed(5):'—');
 const tm=x=>{if(!x)return'—';const d=new Date(x);return Number.isNaN(d.getTime())?'—':d.toLocaleString()};
 window.renderSamsaraFleet=function(){const out=document.getElementById('samsaraFleetResults');if(!out)return;const cache=window.samsaraFleetCache||(typeof samsaraFleetCache!=='undefined'?samsaraFleetCache:[]),q=String(document.getElementById('samsaraFleetSearch')?.value||'').trim().toLowerCase(),rows=cache.filter(v=>!q||[v.name,v.vin,v.licensePlate,v.driver?.name,loc(v)].join(' ').toLowerCase().includes(q));out.innerHTML='<div style="overflow:auto"><table class="table"><thead><tr><th>Vehicle</th><th>VIN / Plate</th><th>Driver</th><th>Engine</th><th>Speed</th><th>Mileage</th><th>Engine Hrs</th><th>Faults</th><th>Last Location</th><th>Updated</th></tr></thead><tbody>'+rows.map(v=>{const n=Number(v.gpsSpeedMph?.value),speed=Number.isFinite(n)?Math.round(n)+' mph':'—',count=Number(v.faultCount||0),fault=v.faultCodes?'<button class="btn btn-sm ittr-fault-btn" data-fault-id="'+esc(v.id)+'" data-fault-name="'+esc(v.name||'Vehicle')+'">⚠️ '+(count||'View')+' Fault Code'+(count===1?'':'s')+'</button>':'None reported';return '<tr><td><b>'+esc(v.name||'—')+'</b><br><span class="muted">'+esc([v.year,v.make,v.model].filter(Boolean).join(' '))+'</span></td><td>'+esc(v.vin||'—')+(v.licensePlate?'<br>'+esc(v.licensePlate):'')+'</td><td>'+esc(v.driver?.name||'—')+'</td><td>'+esc(v.engineModel||'—')+'</td><td>'+esc(speed)+'</td><td>'+(v.odometerMiles!=null?esc(Number(v.odometerMiles).toLocaleString(undefined,{maximumFractionDigits:1})+' mi'):'—')+'</td><td>'+(v.engineHours!=null?esc(Number(v.engineHours).toLocaleString(undefined,{maximumFractionDigits:1})+' h'):'—')+'</td><td>'+fault+'</td><td>'+esc(loc(v))+'</td><td>'+esc(tm(v.gps?.time||v.gpsSpeedMph?.time))+'</td></tr>'}).join('')+'</tbody></table></div>';out.querySelectorAll('[data-fault-id]').forEach(b=>b.onclick=()=>openFaultModal(b.dataset.faultId,b.dataset.faultName))}
})();

function ittrSamsaraV255FaultButton(v){const n=Number(v.faultCount||0),has=!!v.hasDiagnosticData||!!v.faultCodes;if(!has)return 'None reported';const label=n>0?'⚠️ '+n+' Fault Code'+(n===1?'':'s'):'⚠️ View Diagnostics';return '<button type="button" onclick="openSamsaraFaultModal(\''+esc(v.id)+'\',\''+esc(String(v.name||'Vehicle').replace(/'/g,'&#39;'))+'\')" style="background:#fee2e2;color:#b91c1c;border:1px solid #fecaca;border-radius:8px;padding:6px 9px;font-weight:700;cursor:pointer">'+label+'</button>'}
window.renderSamsaraFleet=function(){const out=document.getElementById('samsaraFleetResults');if(!out)return;const cache=(typeof samsaraFleetCache!=='undefined'?samsaraFleetCache:(window.samsaraFleetCache||[])),q=String(document.getElementById('samsaraFleetSearch')?.value||'').trim().toLowerCase(),rows=cache.filter(v=>!q||[v.name,v.vin,v.licensePlate,v.driver?.name,ittrSamsaraLocation(v)].join(' ').toLowerCase().includes(q));out.innerHTML='<div style="overflow:auto"><table class="table"><thead><tr><th>Vehicle</th><th>VIN / Plate</th><th>Driver</th><th>Engine</th><th>Speed</th><th>Mileage</th><th>Engine Hrs</th><th>Faults</th><th>Last Location</th><th>Updated</th></tr></thead><tbody>'+rows.map(v=>{const raw=v.gpsSpeedMph?.value,sp=(raw===null||raw===undefined||raw==='')?null:Number(raw),speed=Number.isFinite(sp)?(Math.round(sp*10)/10)+' mph':'—';return '<tr><td><b>'+esc(v.name||'—')+'</b><br><span class="muted">'+esc([v.year,v.make,v.model].filter(Boolean).join(' '))+'</span></td><td>'+esc(v.vin||'—')+(v.licensePlate?'<br>'+esc(v.licensePlate):'')+'</td><td>'+esc(v.driver?.name||'—')+'</td><td>'+esc(v.engineModel||'—')+'</td><td>'+esc(speed)+'</td><td>'+(v.odometerMiles!=null?esc(Number(v.odometerMiles).toLocaleString(undefined,{maximumFractionDigits:1})+' mi'):'—')+'</td><td>'+(v.engineHours!=null?esc(Number(v.engineHours).toLocaleString(undefined,{maximumFractionDigits:1})+' h'):'—')+'</td><td>'+ittrSamsaraV255FaultButton(v)+'</td><td>'+esc(ittrSamsaraLocation(v))+'</td><td>'+esc(ittrFmtSamsaraTime(v.gps?.time||v.gpsSpeedMph?.time))+'</td></tr>'}).join('')+'</tbody></table></div>'}
