let localAbort=null;
let voiceRecognition=null;
const SUPPORTED={"en-US":"en-US","uk-UA":"uk-UA","pl-PL":"pl-PL","es-ES":"es-ES","ru-RU":"ru-RU"};
function appVoiceLocale(){const chosen=document.getElementById("aiShopVoiceLanguage")?.value||"auto";if(chosen!=="auto")return SUPPORTED[chosen]||"en-US";const lang=String(document.documentElement.lang||navigator.language||"en-US").toLowerCase();if(lang.startsWith("uk"))return "uk-UA";if(lang.startsWith("pl"))return "pl-PL";if(lang.startsWith("es"))return "es-ES";if(lang.startsWith("ru"))return "ru-RU";return "en-US"}
function setBusy(busy,processingId){document.querySelectorAll("#proPanelAitools [data-ai-action]").forEach(b=>b.disabled=busy);document.getElementById(processingId)?.classList.toggle("hidden",!busy)}
async function aiCall(endpoint,payload,processingId){setBusy(true,processingId);try{const r=await fetch(endpoint,{method:"POST",headers:window.authHeaders?.({"Content-Type":"application/json"})||{"Content-Type":"application/json"},body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`AI request failed (${r.status})`);return d.result??d.translation??""}finally{setBusy(false,processingId)}}
window.startVoiceNote=function(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){window.showToast?.("Live dictation requires Chrome or Edge with Web Speech support.","warning",7000);return}if(voiceRecognition){try{voiceRecognition.stop()}catch{}return}const textarea=document.getElementById("aiShopText"),btn=document.getElementById("aiShopMicButton"),state=document.getElementById("aiShopVoiceState");const r=new SR();voiceRecognition=r;r.lang=appVoiceLocale();r.continuous=true;r.interimResults=true;let committed=(textarea?.value||"").trim();r.onstart=()=>{btn?.classList.add("recording");btn?.setAttribute("aria-pressed","true");if(state)state.textContent=`Listening — ${r.lang}`};r.onresult=e=>{let finalChunk="",interim="";for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0]?.transcript||"";if(e.results[i].isFinal)finalChunk+=t+" ";else interim+=t}if(finalChunk.trim())committed=[committed,finalChunk.trim()].filter(Boolean).join(" ");if(textarea)textarea.value=[committed,interim.trim()].filter(Boolean).join(" ");if(state)state.textContent=`Listening — ${r.lang}`};r.onerror=e=>{if(e.error!=="no-speech")window.showToast?.(`Voice dictation: ${e.error}`,"warning",6000)};r.onend=()=>{voiceRecognition=null;btn?.classList.remove("recording");btn?.setAttribute("aria-pressed","false");if(state)state.textContent="Ready for dictation"};try{r.start()}catch(e){voiceRecognition=null;window.showToast?.(e.message,"error")}};
window.aiProfessionalNote=async function(mode="professional"){const el=document.getElementById("aiShopText"),out=document.getElementById("aiShopResult"),text=el?.value.trim();if(!text)return window.showToast?.("Enter or dictate a mechanic note first.","warning");try{const x=await aiCall("/api/ai/note",{text,mode},"aiShopProcessing");if(out)out.textContent=x||""}catch(e){if(out)out.textContent=e.message;window.showToast?.(e.message,"error",7000)}};
window.aiDiagnosticAssistant=async function(){const el=document.getElementById("aiDiagnosticInput"),out=document.getElementById("aiDiagnosticResult"),text=el?.value.trim();if(!text)return window.showToast?.("Enter symptoms or fault codes first.","warning");try{const x=await aiCall("/api/ai/diagnostic",{text},"aiDiagnosticProcessing");if(out)out.textContent=x||""}catch(e){if(out)out.textContent=e.message;window.showToast?.(e.message,"error",7000)}};
window.aiPartAssistant=async function(){const q=document.getElementById("aiPartQuery")?.value.trim(),vin=document.getElementById("aiPartVin")?.value.trim(),out=document.getElementById("aiPartResult");if(!q)return window.showToast?.("Enter a part number or description first.","warning");try{const x=await aiCall("/api/ai/part",{vin,query:q},"aiPartProcessing");if(out)out.textContent=x||""}catch(e){if(out)out.textContent=e.message;window.showToast?.(e.message,"error",7000)}};
export async function mount(scope){localAbort=new AbortController();scope.on(scope.host,"ittr:module-refresh",()=>window.renderProCenter?.(),{passive:true});await window.renderProCenter?.();setTimeout(()=>window.checkAIConnection?.(),0)}
export async function afterShow(){await window.renderProCenter?.()}
export function unmount(){localAbort?.abort();localAbort=null;if(voiceRecognition){try{voiceRecognition.stop()}catch{}voiceRecognition=null}}
