import fs from 'fs';
const h=fs.readFileSync('index.html','utf8'),s=fs.readFileSync('server.js','utf8');let p=0,f=0;const ck=(n,v)=>{console.log((v?'PASS ':'FAIL ')+n);v?p++:f++};
ck('120ms native detection loop',h.includes('}},120);return}if(window.Html5Qrcode)'));
ck('15fps fallback scanner',h.includes('{fps:15,qrbox:{width:320,height:160}'));
ck('HD rear camera requested',h.includes("facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}"));
ck('continuous autofocus attempted',h.includes("focusMode:'continuous'"));
ck('continuous exposure attempted',h.includes("exposureMode:'continuous'"));
ck('ITF and codabar supported when browser supports them',h.includes("'itf','codabar'"));
ck('duplicate decode suppression',h.includes('partsScannerLastCode')&&h.includes('now-partsScannerLastAt<1200'));
ck('GIN alias index created',s.includes('USING GIN (barcode_aliases)'));
ck('internal barcode lower index created',s.includes('idx_fullbay_parts_internal_barcode_lower'));
ck('part number lower index created',s.includes('idx_fullbay_parts_part_number_lower'));
ck('fast alias containment lookup first',s.includes("barcode_aliases @> jsonb_build_array($1::text)"));
ck('case-insensitive legacy fallback preserved',s.includes("jsonb_array_elements_text(coalesce(barcode_aliases,'[]'::jsonb))"));
ck('inventory count fast lookup updated', (s.match(/barcode_aliases @> jsonb_build_array\(\$1::text\)/g)||[]).length>=2);
ck('Fullbay $22 regression guard preserved',s.includes('$22')&&!/fullbay_import_parts[\s\S]{0,1200}\$23/.test(s));
ck('Samsara preserved',s.includes('/api/samsara/fleet'));
ck('Fullbay cleanup preserved',s.includes('/api/fullbay/history/delete-imported'));
console.log(`BARCODE ${p}/${p+f} passed`);if(f)process.exit(1);
