import fs from 'fs';
const s=fs.readFileSync('server.js','utf8'),h=fs.readFileSync('index.html','utf8');
let p=0,f=0;const ck=(n,v)=>{console.log((v?'PASS ':'FAIL ')+n);v?p++:f++};
const ddl=(s.match(/CREATE TABLE IF NOT EXISTS customer_invoices\([\s\S]*?\n \);/)||[''])[0]+(s.match(/ALTER TABLE customer_invoices[\s\S]*?CREATE TABLE IF NOT EXISTS customer_invoice_lines/)||[''])[0];
ck('DDL has tax',/\btax NUMERIC/.test(ddl));
ck('DDL has shop_supplies',ddl.includes('shop_supplies NUMERIC'));
ck('DDL has environmental_fee',ddl.includes('environmental_fee NUMERIC'));
ck('DDL does not define invoice tax_amount',!/\btax_amount\b/.test(ddl));
ck('history query aliases tax correctly',s.includes('i.tax AS tax_amount'));
ck('history query derives fees correctly',s.includes("(coalesce(i.shop_supplies,0)+coalesce(i.environmental_fee,0)) AS additional_fees"));
ck('history query does not reference i.additional_fees',!s.includes('i.additional_fees'));
ck('history query does not reference i.other_charges',!s.includes('i.other_charges'));
ck('draft/sent/partial/paid invoices included',s.includes("WHERE i.status<>'void'"));
ck('invoice history remains Completed service record',s.includes('status:"Completed",invoiceStatus:x.status'));
ck('read-only service history modal remains',h.includes('Service history is read-only.'));
ck('Edit Original Invoice remains source of truth',h.includes('Edit Original Invoice'));
ck('Fullbay history remains',s.includes('source:"fullbay"'));
ck('Samsara remains',s.includes('/api/samsara/fleet'));
ck('barcode performance release remains present',s.includes('idx_fullbay_parts_barcode_aliases_gin') || s.includes('barcode_aliases'));
ck('Fullbay inventory $22 guard preserved',s.includes('$22')&&!/fullbay_import_parts[\s\S]{0,1200}\$23/.test(s));
console.log(`INVOICE HISTORY AUDIT ${p}/${p+f} passed`);if(f)process.exit(1);
