import fs from 'fs';
const s=fs.readFileSync('server.js','utf8'),j=fs.readFileSync('public/modules/procenter.js','utf8');
let p=0,f=0;const ck=(n,v)=>{console.log((v?'PASS ':'FAIL ')+n);v?p++:f++};
ck('duplicate audit uses dot_number',s.includes('c.dot_number AS usdot'));
ck('preview loads customers independently',s.includes("WHERE id=$1',[masterId]")&&s.includes("WHERE id=$1',[duplicateId]"));
ck('preview has safe table allowlist',s.includes("new Set(['customer_units','fullbay_service_history','customer_invoices','service_orders'])"));
ck('preview checks table existence',s.includes("SELECT to_regclass($1) AS name"));
ck('preview no ANY bigint array query',!s.includes("id=ANY($1::bigint[])"));
ck('preview returns stage-specific error',s.includes('Customer merge preview failed during ${stage}.'));
ck('merge transaction remains',s.includes("await db.query('BEGIN')")&&s.includes("await db.query('COMMIT')")&&s.includes("await db.query('ROLLBACK')"));
ck('merge remains owner-only',s.includes("app.post('/api/customers/merge',auth,ownerOnly"));
ck('merge relinks units/history',s.includes('UPDATE customer_units SET customer_id=$1')&&s.includes('UPDATE fullbay_service_history SET customer_id=$1'));
ck('merge relinks optional invoice/order tables when present',s.includes("to_regclass('public.customer_invoices')")&&s.includes("to_regclass('public.service_orders')"));
ck('typed MERGE protection remains',j.includes("typed!=='MERGE'"));
ck('second confirmation remains',j.includes("confirm('This will relink"));
ck('lazy route exports remain',j.includes('window.previewDuplicateMerge')&&j.includes('window.commitDuplicateMerge'));
ck('Samsara secret remains server-side',s.includes('process.env.SAMSARA_API_TOKEN'));
ck('Fullbay $22 regression guard remains',s.includes('$22')&&!/fullbay_import_parts[\s\S]{0,1200}\$23/.test(s));
console.log(`DEEP ${p}/${p+f} passed`);if(f)process.exit(1);
