import fs from 'fs';
const s=fs.readFileSync('server.js','utf8'),j=fs.readFileSync('public/modules/procenter.js','utf8');
let p=0,f=0;const ck=(n,v)=>{console.log((v?'PASS ':'FAIL ')+n);v?p++:f++};
const block=(s.match(/v24\.23\.1 — safe cleanup[\s\S]*?app\.get\(["']\/api\/build/)||[''])[0];
ck('cleanup owner only',block.includes("delete-imported',auth,ownerOnly"));
ck('cleanup only deletes service history',block.includes('DELETE FROM fullbay_service_history'));
ck('cleanup source scope is fullbay keys',block.includes("LIKE 'fullbay:%'"));
ck('cleanup does not delete customers',!block.includes('DELETE FROM fullbay_import_customers'));
ck('cleanup does not delete units',!block.includes('DELETE FROM customer_units'));
ck('cleanup does not delete invoices',!block.includes('DELETE FROM customer_invoices'));
ck('cleanup does not delete work orders',!block.includes('DELETE FROM work_orders'));
ck('typed confirmation',block.includes("confirmation!=='DELETE FULLBAY HISTORY'"));
ck('second UI confirmation',j.includes("confirm('Delete ONLY the previously imported Fullbay service-history rows?"));
ck('existing service history importer remains',s.includes('/api/fullbay/import/service-history'));
ck('Fullbay detailed viewer remains',s.includes('/api/fullbay/service-orders/:so'));
ck('invoice completed history remains',s.includes('status:"Completed",invoiceStatus:x.status'));
ck('Samsara remains',s.includes('/api/samsara/fleet'));
ck('Fullbay $22 guard remains',s.includes('$22')&&!/fullbay_import_parts[\s\S]{0,1200}\$23/.test(s));
console.log(`CLEANUP AUDIT ${p}/${p+f} passed`);if(f)process.exit(1);
