import fs from 'fs';
const h=fs.readFileSync('public/index.html','utf8'),s=fs.readFileSync('server.js','utf8'),
 i=fs.readFileSync('public/modules/invoices.js','utf8'),ih=fs.readFileSync('public/modules/invoices.html','utf8'),
 p=fs.readFileSync('public/modules/parts.js','utf8'),ph=fs.readFileSync('public/modules/procenter.html','utf8'),sw=fs.readFileSync('public/sw.js','utf8');
let ok=0,fail=0;const c=(n,v)=>{console.log((v?'PASS ':'FAIL ')+n);v?ok++:fail++};
c('version 24.24.0',h.includes("24.24.0")&&s.includes("24.24.0"));
c('WO sync UI',h.includes('Sync from Work Order'));
c('WO sync endpoint',s.includes("/sync-work-order"));
c('WO sync imports sessions',s.includes('task_time_sessions'));
c('WO sync imports task parts',s.includes("Array.isArray(t.parts)"));
c('WO sync transactional',s.includes("invoice_synced_from_work_order"));
c('fleet tier persisted',s.includes("fleet_tier=$24"));
c('retail matrix',h.includes("partsMarkup:30"));
c('preferred matrix',h.includes("partsMarkup:20")&&h.includes("discount:5"));
c('national matrix',h.includes("partsMarkup:15")&&h.includes("discount:10"));
c('partial payment API retained',s.includes("/payments"));
c('running balance retained',h.includes("invPreviewBalance"));
c('print rules retained',ih.includes("@media print"));
c('52px touch target',h.includes("min-height:52px!important;font-size:16px!important;padding:16px!important"));
c('emerald active',h.includes("--job-active:#067647"));
c('amber paused',h.includes("--job-paused:#b54708"));
c('rose hold',h.includes("--job-hold:#b42318"));
c('indigo complete',h.includes("--job-completed:#3538cd"));
c('receiving 50/50',h.includes("grid-template-columns:minmax(0,1fr) minmax(0,1fr)"));
c('receiving zoom',h.includes("receivingZoom("));
c('receiving rotate',h.includes("receivingRotate()"));
c('receiving reset',h.includes("receivingResetView()"));
c('price variance >5',h.includes("rise>5"));
c('parts receiving contract',p.includes("varianceWarningPct:5"));
c('speech recognition',h.includes("webkitSpeechRecognition"));
c('voice languages EN UA PL ES',["en-US","uk-UA","pl-PL","es-ES"].every(x=>h.includes(x)));
c('recording indicator',h.includes("Listening…"));
c('sync badge correct id/css',h.includes("#sync-queue-badge{")&&h.includes('id="sync-queue-badge"'));
c('persistent local sync queue',h.includes("ittr_sync_queue_v2"));
c('online auto flush',h.includes('addEventListener("online"')&&h.includes("flushPersistentSyncQueue"));
c('toast region',h.includes('id="toastRegion"'));
c('raw app-error absent',!h.includes('id="app-error"'));
c('production SW registers',h.includes("serviceWorker.register('/sw.js'"));
c('SW does not self-unregister',!sw.includes("unregister()"));
c('SW shell cache',sw.includes("const SHELL="));
c('SW excludes API mutation caching',sw.includes("startsWith('/api/')"));
c('background sync request',sw.includes("ITTR_SYNC_REQUEST"));
c('Fullbay $22 guard retained',s.includes('$22')&&!/fullbay_import_parts[\s\S]{0,1200}\$23/.test(s));
c('Samsara retained',s.includes('/api/samsara/fleet'));
c('barcode aliases retained',s.includes('barcode_aliases'));
c('invoice service history retained',s.includes('i.tax AS tax_amount'));
console.log(`ENTERPRISE PWA AUDIT ${ok}/${ok+fail} passed`);if(fail)process.exit(1);
