import fs from 'node:fs';
const sp='server.js';let s=fs.readFileSync(sp,'utf8');
const start=s.indexOf("app.get('/api/samsara/fleet',auth,managerPermission('customers'),async(req,res)=>{");
const end=s.indexOf('function samsaraNormVin',start);
if(start<0||end<0)throw new Error('v24.25.3 fleet boundary not found');
const route=String.raw`app.get('/api/samsara/fleet',auth,managerPermission('customers'),async(req,res)=>{
 try{
  const vehicles=await samsaraPaged('/fleet/vehicles'),warnings=[];
  async function opt(label,path,params){try{return await samsaraPaged(path,params)}catch(e){console.warn('[Samsara '+label+']',e?.status||'',e?.message||e);warnings.push({source:label,status:Number(e?.status)||null,message:e?.message||String(e)});return []}}
  // Samsara Vehicle Stats allows at most 3 stat types/request. Keep these calls separated.
  const [gpsStats,odoStats,diagStats,drivers]=await Promise.all([
   opt('GPS / speed','/fleet/vehicles/stats',{types:'gps,ecuSpeedMph'}),
   opt('Mileage / engine hours','/fleet/vehicles/stats',{types:'obdOdometerMeters,obdEngineSeconds'}),
   opt('Fault codes','/fleet/vehicles/stats',{types:'faultCodes'}),
   opt('Drivers','/fleet/drivers')
  ]);
  const by=(rows)=>new Map(rows.map(x=>[String(x.id||x.vehicle?.id||''),x]));
  const gm=by(gpsStats),om=by(odoStats),xm=by(diagStats),dm=new Map(drivers.map(d=>[String(d.id),d]));
  const last=x=>Array.isArray(x)?(x[x.length-1]||null):x;
  const n=x=>{const z=last(x);const v=Number(z?.value??z);return Number.isFinite(v)?v:null};
  const faultReading=x=>last(x?.faultCodes)||null;
  const faultArray=reading=>{if(!reading)return[];const root=reading.value??reading;const j=root.j1939?.diagnosticTroubleCodes??root.j1939?.dtcs??root.j1939??root.diagnosticTroubleCodes??root.activeDiagnosticTroubleCodes??[];return Array.isArray(j)?j:[]};
  const items=vehicles.map(v=>{const id=String(v.id),g=gm.get(id)||{},o=om.get(id)||{},x=xm.get(id)||{},gps=last(g.gps),ecu=n(g.ecuSpeedMph),obd=n(o.obdOdometerMeters),seconds=n(o.obdEngineSeconds),reading=faultReading(x),faults=faultArray(reading),did=String(v.staticAssignedDriver?.id||v.driver?.id||''),driver=dm.get(did)||v.staticAssignedDriver||v.driver||null;const gpsSpeed=Number(gps?.speedMilesPerHour??gps?.speedMph);return{id:v.id,name:v.name||'',vin:v.vin||'',make:v.make||'',model:v.model||'',year:v.year||'',licensePlate:v.licensePlate||'',engineModel:v.engineModel||v.engine?.model||v.attributes?.engineModel||'',driver:driver?{id:driver.id||did,name:driver.name||[driver.firstName,driver.lastName].filter(Boolean).join(' '),phone:driver.phone||''}:null,gps:gps?{time:gps.time||gps.timestamp||'',latitude:gps.latitude,longitude:gps.longitude,headingDegrees:gps.headingDegrees,reverseGeo:gps.reverseGeo||null,location:gps.reverseGeo?.formattedLocation||gps.address||gps.formattedLocation||''}:null,gpsSpeedMph:{value:ecu??(Number.isFinite(gpsSpeed)?gpsSpeed:null),time:last(g.ecuSpeedMph)?.time||gps?.time||''},odometerMiles:obd==null?null:Math.round((obd/1609.344)*10)/10,odometerSource:obd==null?'':'ECU/OBD',engineHours:seconds==null?null:Math.round((seconds/3600)*10)/10,faultCount:faults.length,faultCodes:reading};});
  res.set('Cache-Control','no-store');res.json({ok:true,items,updatedAt:new Date().toISOString(),warnings});
 }catch(e){console.error('[Samsara fleet v24.25.3]',e);res.status(Number(e?.status)||500).json({ok:false,error:'Samsara vehicle list failed',detail:e?.message||String(e),build:'24.25.3'})}
});

app.get('/api/samsara/vehicle-faults',auth,async(req,res)=>{
 try{const vehicleId=String(req.query.vehicleId||'').trim();if(!vehicleId)return res.status(400).json({ok:false,error:'vehicleId is required'});const rows=await samsaraPaged('/fleet/vehicles/stats',{types:'faultCodes',vehicleIds:vehicleId}),row=rows.find(r=>String(r.id||r.vehicle?.id||'')===vehicleId)||rows[0]||null,reading=Array.isArray(row?.faultCodes)?row.faultCodes[row.faultCodes.length-1]:row?.faultCodes||null,root=reading?.value??reading??{},j=root.j1939?.diagnosticTroubleCodes??root.j1939?.dtcs??root.j1939??root.diagnosticTroubleCodes??root.activeDiagnosticTroubleCodes??[],arr=Array.isArray(j)?j:[],faults=arr.map(z=>({spn:z.suspectParameterNumber??z.spn??null,fmi:z.failureModeIdentifier??z.fmi??null,description:z.description??z.name??z.label??z.faultDescription??'',occurrenceCount:z.occurrenceCount??z.count??null,sourceAddress:z.sourceAddress??null,active:z.active!==false})).filter(z=>z.spn!=null||z.fmi!=null||z.description);res.set('Cache-Control','no-store');res.json({ok:true,vehicleId,vehicleName:row?.name||'',time:reading?.time||reading?.timestamp||'',count:faults.length,faults,raw:reading});}catch(e){res.status(Number(e?.status)||500).json({ok:false,error:'Unable to load Samsara fault codes',detail:e?.message||String(e),build:'24.25.3'})}
});

`;
s=s.slice(0,start)+route+s.slice(end);fs.writeFileSync(sp,s);

const fp='public/modules/procenter.js';let f=fs.readFileSync(fp,'utf8');
// Override renderer after prior runtime patches: use normalized production fields and interactive faults.
f+=String.raw`
function ittrFmtSamsaraTime(x){if(!x)return '—';const d=new Date(x);return Number.isNaN(d.getTime())?'—':d.toLocaleString()}
function ittrSamsaraLocation(v){const g=v?.gps;if(!g)return '—';return g.reverseGeo?.formattedLocation||g.location||((g.latitude!=null&&g.longitude!=null)?Number(g.latitude).toFixed(5)+', '+Number(g.longitude).toFixed(5):'—')}
window.openSamsaraFaultModal=async function(vehicleId,vehicleName){let m=document.getElementById('samsaraFaultModal');if(!m){m=document.createElement('div');m.id='samsaraFaultModal';m.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:100000;display:none;align-items:center;justify-content:center;padding:18px';m.innerHTML='<div style="background:#fff;color:#111;width:min(900px,96vw);max-height:88vh;overflow:auto;border-radius:14px;padding:20px;box-shadow:0 20px 60px #0005"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><h2 id="samsaraFaultTitle" style="margin:0">Fault Codes</h2><button class="btn" onclick="document.getElementById(\'samsaraFaultModal\').style.display=\'none\'">Close</button></div><div id="samsaraFaultBody" style="margin-top:14px"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.style.display='none'})}m.style.display='flex';document.getElementById('samsaraFaultTitle').textContent=(vehicleName||'Vehicle')+' · Active Fault Codes';const body=document.getElementById('samsaraFaultBody');body.innerHTML='<div class="muted">Loading live diagnostic reading…</div>';try{const d=await apiJSON('/api/samsara/vehicle-faults?vehicleId='+encodeURIComponent(vehicleId));if(!d.faults?.length){body.innerHTML='<div class="notice">No active J1939 SPN/FMI codes were returned in the latest Samsara reading.</div>';return}body.innerHTML='<div class="muted" style="margin-bottom:10px">Latest reading: '+esc(ittrFmtSamsaraTime(d.time))+'</div><div style="overflow:auto"><table class="table"><thead><tr><th>SPN</th><th>FMI</th><th>Description</th><th>Occurrences</th><th>Status</th></tr></thead><tbody>'+d.faults.map(z=>'<tr><td><b>'+esc(z.spn??'—')+'</b></td><td>'+esc(z.fmi??'—')+'</td><td>'+esc(z.description||'—')+'</td><td>'+esc(z.occurrenceCount??'—')+'</td><td>'+(z.active===false?'Inactive':'Active')+'</td></tr>').join('')+'</tbody></table></div>'}catch(e){body.innerHTML='<div class="notice error">'+esc(e.message||String(e))+'</div>'}}
window.renderSamsaraFleet=function(){const out=document.getElementById('samsaraFleetResults');if(!out)return;const q=String(document.getElementById('samsaraFleetSearch')?.value||'').trim().toLowerCase(),rows=(window.samsaraFleetCache||samsaraFleetCache||[]).filter(v=>!q||[v.name,v.vin,v.licensePlate,v.driver?.name,ittrSamsaraLocation(v)].join(' ').toLowerCase().includes(q));out.innerHTML='<div style="overflow:auto"><table class="table"><thead><tr><th>Vehicle</th><th>VIN / Plate</th><th>Driver</th><th>Engine</th><th>Speed</th><th>Mileage</th><th>Engine Hrs</th><th>Faults</th><th>Last Location</th><th>Updated</th></tr></thead><tbody>'+rows.map(v=>{const sp=Number(v.gpsSpeedMph?.value),speed=Number.isFinite(sp)?sp.toFixed(sp%1?1:0)+' mph':'—',fc=Number(v.faultCount||0),faultBtn=fc>0?'<button class="btn btn-sm" onclick="openSamsaraFaultModal(\''+esc(v.id)+'\',\''+esc(String(v.name||'').replace(/'/g,'&#39;'))+'\')">⚠️ '+fc+' Fault Code'+(fc===1?'':'s')+'</button>':(v.faultCodes?'<button class="btn btn-sm" onclick="openSamsaraFaultModal(\''+esc(v.id)+'\',\''+esc(String(v.name||'').replace(/'/g,'&#39;'))+'\')">View diagnostics</button>':'None reported');return '<tr><td><b>'+esc(v.name||'—')+'</b><br><span class="muted">'+esc([v.year,v.make,v.model].filter(Boolean).join(' '))+'</span></td><td>'+esc(v.vin||'—')+(v.licensePlate?'<br>'+esc(v.licensePlate):'')+'</td><td>'+esc(v.driver?.name||'—')+'</td><td>'+esc(v.engineModel||v.engineState||'—')+'</td><td>'+esc(speed)+'</td><td>'+(v.odometerMiles!=null?esc(Number(v.odometerMiles).toLocaleString(undefined,{maximumFractionDigits:1})+' mi'):'—')+'</td><td>'+(v.engineHours!=null?esc(Number(v.engineHours).toLocaleString(undefined,{maximumFractionDigits:1})+' h'):'—')+'</td><td>'+faultBtn+'</td><td>'+esc(ittrSamsaraLocation(v))+'</td><td>'+esc(ittrFmtSamsaraTime(v.gps?.time||v.gpsSpeedMph?.time))+'</td></tr>'}).join('')+'</tbody></table></div>'}
`;
fs.writeFileSync(fp,f);if(fs.existsSync('modules/procenter.js'))fs.copyFileSync(fp,'modules/procenter.js');console.log('ITTR Samsara v24.25.3 production stats + fault modal applied');