import fs from 'node:fs';
const path='server.js';
let s=fs.readFileSync(path,'utf8');
const old="function samsaraSnapshot(v){const g=v?.location||v?.gps||{},d=v?.driver||v?.staticAssignedDriver||{};return{id:String(v?.id||''),name:String(v?.name||''),vin:samsaraNormVin(v?.vin),unit:String(v?.name||''),plate:String(v?.licensePlate||v?.licensePlateNumber||''),make:String(v?.make||''),model:String(v?.model||''),year:String(v?.year||''),driverName:String(d?.name||v?.driverName||''),location:String(g?.formattedLocation||g?.address||''),latitude:Number(g?.latitude??g?.lat??0)||null,longitude:Number(g?.longitude??g?.lng??0)||null,speedMph:Number(g?.speedMilesPerHour??g?.speedMph??0)||null,ignition:String(v?.engineState?.value||v?.engineState||v?.ignitionStatus||''),lastSeen:String(g?.time||g?.timestamp||v?.updatedAtTime||'')||null}}";
const replacement="function samsaraParseUnitName(name){const raw=String(name||'').trim(),m=raw.match(/^([^\\s\\/]+)\\s*\\/\\s*([^\\s]+)(?:\\s+(.+))?$/);return m?{raw,truckNumber:String(m[1]||'').trim(),trailerNumber:String(m[2]||'').trim(),labelRemainder:String(m[3]||'').trim()}:{raw,truckNumber:raw,trailerNumber:'',labelRemainder:''}}\nfunction samsaraSnapshot(v){const g=v?.location||v?.gps||{},d=v?.driver||v?.staticAssignedDriver||{},parsed=samsaraParseUnitName(v?.name);return{id:String(v?.id||''),name:String(v?.name||''),vin:samsaraNormVin(v?.vin),unit:parsed.truckNumber,truckNumber:parsed.truckNumber,trailerNumber:parsed.trailerNumber,labelRemainder:parsed.labelRemainder,plate:String(v?.licensePlate||v?.licensePlateNumber||''),make:String(v?.make||''),model:String(v?.model||''),year:String(v?.year||''),driverName:String(d?.name||v?.driverName||parsed.labelRemainder||''),location:String(g?.formattedLocation||g?.address||''),latitude:Number(g?.latitude??g?.lat??0)||null,longitude:Number(g?.longitude??g?.lng??0)||null,speedMph:Number(g?.speedMilesPerHour??g?.speedMph??0)||null,ignition:String(v?.engineState?.value||v?.engineState||v?.ignitionStatus||''),lastSeen:String(g?.time||g?.timestamp||v?.updatedAtTime||'')||null}}";
if(s.includes(old))s=s.replace(old,replacement);else if(!s.includes('function samsaraParseUnitName('))throw new Error('Samsara snapshot signature changed');
s=s.replaceAll("build:'24.24.5'","build:'24.24.6'");
fs.writeFileSync(path,s);
console.log('Samsara truck/trailer parser applied');
