import fs from 'node:fs';

// v24.26.0 compatibility patch. The repository may already contain the corrected
// invoice workspace opener after a prior boot/build. Startup must remain idempotent
// and must never take the entire Railway web service down because an old text
// signature changed.
const files=['public/index.html','index.html'];
const oldFn=`function openInvoiceWorkspace(id){
  const url=invoiceWorkspaceUrl(id);
  // Open as a normal isolated browser tab; authentication is handed off
  // over a same-origin BroadcastChannel, so no credentials are placed in the URL.
  const link=document.createElement('a');
  link.href=url;
  link.target='_blank';
  document.body.appendChild(link);
  link.click();
  link.remove();
}`;
const newFn=`function openInvoiceWorkspace(id){
  const invoiceId=Number(id||0);
  if(!invoiceId)return;
  const url=invoiceWorkspaceUrl(invoiceId);
  let tab=null;
  try{tab=window.open(url,'_blank')}catch(_){tab=null}
  if(!tab){
    openInvoice(invoiceId,false);
    return;
  }
  try{tab.focus()}catch(_){ }
}`;

for(const fp of files){
  if(!fs.existsSync(fp)){
    console.warn('[ITTR startup] '+fp+' missing; skipping invoice workspace compatibility patch');
    continue;
  }
  let s=fs.readFileSync(fp,'utf8');
  if(s.includes(oldFn)){
    s=s.replace(oldFn,newFn);
    fs.writeFileSync(fp,s);
    console.log('[ITTR startup] invoice workspace compatibility patch applied to '+fp);
    continue;
  }
  // Already fixed, refactored, or generated by a newer release: preserve it.
  if(/function\s+openInvoiceWorkspace\s*\(/.test(s)){
    console.log('[ITTR startup] '+fp+' already has an invoice workspace opener; preserving current implementation');
  }else{
    console.warn('[ITTR startup] invoice workspace opener not found in '+fp+'; skipping legacy patch safely');
  }
}
