import fs from 'fs';
const s=fs.readFileSync('server.js','utf8');let p=0,f=0;
const c=(n,v)=>{console.log((v?'PASS ':'FAIL ')+n);v?p++:f++};
const block=s.slice(s.indexOf('// ===== v24.24.5: Samsara'),s.indexOf("app.get('/api/samsara/vehicle/:id/history'"));
c('release 24.24.5',s.includes("build:'24.24.5'"));
c('raw token helper',s.includes('function getSamsaraToken()'));
c('Bearer prefix stripped',s.includes("replace(/^Bearer\\s+/i,''"));
c('quoted token normalized',s.includes('token.slice(1,-1).trim()'));
c('token never exposed by diagnostics',!block.includes('tokenValue')&&!block.includes('rawToken'));
c('Samsara request uses normalized token',block.includes('const token=getSamsaraToken()'));
c('401 is explicit',block.includes('HTTP 401'));
c('403 permission is explicit',block.includes('HTTP 403')&&block.includes('Read Vehicles'));
c('correct customer schema',block.includes('c.customer_name AS customer_name'));
c('bad c.name join removed',!block.includes('c.name customer_name'));
c('all-units order uses customer_name',block.includes('ORDER BY c.customer_name,u.unit_number'));
c('VIN-first matching retained',block.includes("method='vin'"));
c('unit fallback retained',block.includes("method='unit'"));
c('no auto customer inserts',!block.includes('INSERT INTO fullbay_import_customers'));
c('Fullbay inventory $22 guard',s.includes('$22'));
console.log(`${p}/${p+f} passed`);if(f)process.exit(1);
